@baseUrl = http://localhost:4004

# Get Service Document
GET {{baseUrl}}/admin/$metadata
### -----------------------------------------------

# Post Practice
POST {{baseUrl}}/admin/Practices
Content-Type: application/json

{
    "practiceCode": "BAC",
    "practice": "Back-Office"
}
### -----------------------------------------------

# Post Office
POST {{baseUrl}}/admin/Offices
Content-Type: application/json

{
    "officeCode": "MEL",
    "office": "Melbourne"
}
### -----------------------------------------------

# Post seniority
POST {{baseUrl}}/admin/Seniorities
Content-Type: application/json

{
    "seniorityCode": "ASC",
    "seniority": "Associate"
}
### -----------------------------------------------

# Post Employment
POST {{baseUrl}}/admin/Employments
Content-Type: application/json

{
    "employmentCode": "INT",
    "employment": "Intern"
}
### -----------------------------------------------

# Post Role
POST {{baseUrl}}/admin/Roles
Content-Type: application/json

{
    "roleCode": "ADM",
    "role": "Administrator"
}
### -----------------------------------------------

# Post Employee
POST {{baseUrl}}/admin/Employees
Content-Type: application/json

{
    "firstName": "David",
    "lastName": "Tangarife",
    "practice": {"ID":"4e512a88-5755-40d5-824f-374ae30d4613"},
    "office": {"ID":"dc3d6d9c-5594-4d99-be27-d322eb0e5198"},
    "seniority": {"ID":"2181df80-8f97-4007-8660-20aef7c56d10"}, 
    "employment": {"ID":"d22a2594-3b21-4c60-a862-fb6033c0dc0f"},
    "role": {"ID":"ac9981ef-4957-44a4-a862-b3d246628d7e"},
    "email": "david.tangarife@faircg.com",
    "salary": 0
}
### -----------------------------------------------

# Post Skill
POST {{baseUrl}}/admin/Skills
Content-Type: application/json

{
    "skillCode": "SAP-CAP",
    "skill": "Cloud Application Programming Model",
    "parentSkill": null
}
### -----------------------------------------------

# Delete Employee
DELETE {{baseUrl}}/admin/Employees('b13f2159-c6bb-4556-bbdc-d89e47e72818')
### -----------------------------------------------


